export { configureTestKernels, startTestKernel, testTables, createIdentity, withDependencies } from "./testing/startTestKernel";
export { findImportViolations, findCopiedVocabulary, findSharedNames, findSplitVocabulary, findUnscopedReach } from "./testing/boundaries";
export { findMigrationDrift, findSqliteOnlyCalls } from "./testing/dialects";
export { findMissingDocs, findOversizedDocs, findUndocumentedKeys, findUnexplainedPlugins } from "./testing/docs";
export { Project } from "./testing/project";
export { StoredContracts } from "./testing/storedContracts";
export { testClock } from "./testing/testClock";
export type { TestClock } from "./testing/testClock";
export { Started } from "./testing/started";
export { findUnusedFields } from "./testing/wiring";

export type { TestKernel, TestKernelDefaults, TestKernelFixture, TestKernelOptions, SeenEvent, SentRequest, LogLine } from "./testing/startTestKernel";
export type { Identity, HttpRequest } from "./plugins/kernel/api";
export type { ImportEdge, ImportViolation, CopiedVocabulary, DuplicateSignature, SplitVocabulary } from "./testing/boundaries";
export type { DialectFinding } from "./testing/dialects";
export type { OversizedDoc, UndocumentedKey } from "./testing/docs";
export type { ProjectCheckOptions, ProjectProblem } from "./testing/project";
export type { Breach, Lock } from "./testing/storedContracts";
export type { StartedCheckOptions, StartedProblem } from "./testing/started";
export type { UnusedField } from "./testing/wiring";
